const data = [
  {
    id: 1,
    url: "massage-fertilite",
    image: "massage_fertilite.jpeg",
    title: "Massage fertilité",
    content: [
      `Le massage "fertilité" est un soin bien être à but non thérapeutique dédié à la femme qui rencontre des difficultés dans son désir d'enfant. Il s'agit d'un massage qui stimule la circulation sanguine, qui soutient et soulage les crampes lors de l'ovulation et les douleurs liées à l'endométriose ou encore au SOPK (syndrome des ovaires polykystiques).
        `,
      `Ce soin débutera par un temps d'échange autour de votre parcours, suivi d'un temps de visualisation autour de l'appareil reproducteur pour que vous puissiez apprendre à connaître votre corps et à le conscientiser.`,
      `Une technique de bercement au rebozo vous sera proposée puis un temps de massage ventral vous sera offert ainsi qu'un temps d'accupression et de réflexologie spécial fertilité.`,
      `Nous terminerons le soin avec un temps de transmissions et d'échanges autour de l'alimentation et d'un protocole de massage pré ovulatoire à réaliser seule ou en couple.`,
      `Ce soin est réalisé sur mesure en fonction de votre histoire, vos besoins, votre parcours.`,
      `Il est idéal avant toute préconception pour apprendre à connaître son propre corps et pour stimuler/harmoniser le système reproducteur.`,
      `Il peut être complémentaire à la vie d'une femme qui mène un parcours et un désir d'enfant sensible par exemple en PMA (demandez toujours un avis médical avant de vous lancer dans un protocole de massage)`,
      `Il est l'occasion pour la femme qui a vécu une interruption volontaire ou non de grossesse de se réapproprier cette zone.`,
      `Il soutient les femmes en général (trompes bouchées, fibromes, adhésions, tissus cicatriciel, infertilité inexpliquée, caillots durant les règles, kystes, endometriose, mauvaise circulation sanguine....)`,
      `Le massage ventral se fait uniquement après vos règles et juste avant l'ovulation.
        Je ne masse pas le ventre pendant vos règles et en période post ovulatoire`,
    ],
    prestations: ["à domicile", "en cabinet"],
    duration: "1h15",
    price: "70 euros",
    infos: [],
  },
  {
    id: 2,
    url: "massage-femme-enceinte",
    image: "massage_femme_enceinte.jpeg",
    title: "Le massage femme enceinte",
    content: [
      `"Pour materner, il faut être maternée"`,
      `Convaincue de la force et la puissance des Femmes, du corps de la femme et de ses ressources, j'accompagne les femmes au quotidien à (re)découvrir qu'elles ont tout en elles pour donner naissance à leur enfant.`,
      `Ce massage est un soin dédié à la femme enceinte à but non thérapeutique qui permet de détendre, d'apaiser, de libérer les tensions et de soulager les différents maux de la grossesse (tensions du dos, sensations de tiraillement au niveau du plancher pelvien, sensation d'étouffement...). Il permet également à la maman de prendre conscience de son corps et d'accepter les différents changements corporels survenus durant la grossesse.`,
      `C'est un soin qui débute par un temps d'accueil et d'échanges autour d'une tisane chaude adaptée à votre stade de grossesse.`,
      `Vous êtes ensuite bercée délicatement à l'aide d'un rebozo mexicain. Une véritable enveloppe de douceur.`,
      `Un temps de massage exclusif et non invasif du corps complet à l'huile chaude bio (première pression à froid, sans perturbateurs endocriniens) vous est offert. Ce massage respecte votre corps, votre intimité et votre bébé. Installée en fonction de vos besoins à l'aide de coussins, d'un coussin d'allaitement à disposition et recouverte d'une serviette, ce massage vous assure un confort idéal sur une table de massage chauffée.`,
      `Il se termine par de légers bercements pour vous connecter sensoriellement à votre bébé.`,
      `Et comme je suis attentive à l'environnement de la femme enceinte et à sa sécrétion d'ocytocine pour elle et son bébé, je vous offre une atmosphère enveloppante et mélodieuse pour vous faire décompresser et atterrir dans un océan de douceur.`,
      `Le soin peut être réalisé à partir du 2ème trimestre de grossesse jusqu'à la naissance`,
    ],
    prestations: ["à domicile", "en cabinet"],
    duration: "1h15",
    price: "70 euros",
    infos: [
      `Contre-indications :  fièvre, hypertension ou vaccin de moins de 48h. En cas de doute demandez toujours l'avis de votre professionnel de santé de référence.`,
    ],
  },
  {
    id: 3,
    url: "réflexologie-femme-enceinte",
    image: "reflexologie_detente_femme_enceinte.png",
    title: "Réflexologie détente de la femme enceinte",
    content: [
      `Véritable accompagnement psycho-affectif, le protocole réflexologie "détente" de la femme enceinte vous accompagnera tout au long de la grossesse pour vous détendre et vous sentir plus sereine.`,
      `C'est un temps de soin qui peut également être partagé avec le co/parent pour lui permettre de prendre sa place durant la grossesse et de vivre un moment complice qui peut devenir un rituel bien être en couple.`,
      `Ce soin comprend :`,
      `Un temps d'accueil et d'échanges sur vos besoins`,
      `Un temps de réflexologie donné par mes soins ou de transmission (si présence du co-parent) accompagné d'une couverture douce sur le reste du corps.`,
      `Ce soin vous est proposé à partir du 2ème trimestre jusqu'à la fin de grossesse et peut se faire quotidiennement.`,
      `Il est aussi adapté après l'accouchement`,
    ],
    prestations: ["à domicile", "en cabinet"],
    duration: "45 min",
    price: "45 euros",
    infos: [],
  },
  {
    id: 4,
    url: "decouverte-portage-physiologique",
    image: "portage.png",
    title: "Atelier découverte du portage physiologique",
    content: [
      `Lors de cet atelier, vous partirez à la découverte du portage physiologique et vous pourrez poser toutes les questions nécessaires au portage de bébé.`,
      `Avant que bébé arrive, vous êtes envahi d'une liste de naissance à créer, d'une poussette à acheter ? Vous avez repéré ou entendu parler du portage de près ou de loin ? `,
      `Vous êtes déjà parent et vous avez déjà porter bébé à l'aide d'un porte bébé dit "non physiologique" ? Vous souhaitez découvrir la physiologie et son intérêt pour bébé ? `,
      `Lors de cet atelier nous aborderons dans un premier temps ce qu'est le portage, sa physiologie, ses intérêts pour vous et votre bébé. C'est de façon ludique que vous découvrirez quand, comment, où et pourquoi porter.`,
      `Vous serez initié au portage à bras physiologique et à l'emmaillotage physiologique. Vous pourrez d'ailleurs pratiquer sur poupon ou sur votre bébé. `,
      `Puis vous découvrirez les différents moyens de portage du monde et pourrez tester des indispensables pour des débuts de portage tout en douceur. `,
      `Un mélange de pratique, d'échanges et de transmission... `,
    ],
    prestations: ["à domicile", "en cabinet"],
    duration: "2 heures",
    price: "50 euros",
    infos: [],
  },
  {
    id: 5,
    url: "decouverte-allaitement",
    image: "allaitement.png",
    title: "Atelier découverte de l'allaitement",
    content: [
      `Vous êtes enceinte et vous vous demandez comment vous alimenterez bébé ? `,
      `Vous avez besoin de vous informer ? Vous souhaitez allaiter mais vous avez des doutes ? Allaitement ? Pas allaitement ? Tire-lait, engorgement, positions... ? Vous avez déjà allaité et vous n'avez pas été ou pas suffisamment informée, accompagnée ? `,
      `Vous souhaitez vous informer seule ou en couple ? `,
      `Avec l'atelier découverte de l'allaitement, nous avancerons ensemble autour d'échanges libres et de transmission autour de l'allaitement.`,
      `Nous balayerons ensemble tous les sujets qui gravitent autour de l'allaitement et nous essayerons de déconstruire les mythes afin que vous puissiez être suffisamment informée et libre de faire vos propres choix. `,
      `Autour d'une boisson découverte spéciale allaitement, dans une ambiance intimiste et non jugeante, nous ferons le point sur vos besoins, vos envies, vos questionnements, vos peurs et vous désirs. `,
      `Puis nous verrons ensemble comment favoriser des débuts d'allaitement sereins.`,
      `Vous repartirez avec des clés concrètes et une réassurance en votre corps et en vos capacités à nourrir votre enfant de la manière qui vous convient.`,
    ],
    prestations: ["à domicile", "en cabinet"],
    duration: "1 heure",
    price: "35 euros",
    infos: [],
  },
  {
    id: 6,
    url: "parent-coach",
    image: "papa_coach.jpeg",
    title: "Atelier papa/parent coach",
    content: [
      `"S'impliquer dans la grossesse et créer du lien avec son bébé"`,
      `L'ATELIER PAPA/PARENT COACH est un atelier dédié au couple autour de la grossesse, des changements physiques et psychiques liés à la grossesse et de la création de lien avec bébé.`,
      `C'est l'occasion pour le co-parent de recevoir une transmission autour d'un bon nombre d'outils pratiques tels que le rebozo, le massage, les bercements, les postures qui lui permettront de se sentir investi dans la grossesse, d'accompagner sa compagne au quotidien et dans la gestion de la douleur mais aussi de prendre plus facilement sa place en tant que père/mère.`,
      `C'est un atelier qui permet également d'inclure la fratrie (si vous m'en faites la demande) autour d'un protocole de massage bien être de la mère afin de préparer la famille à l'arrivée de ce petit être humain et de booster l'ocytocine chez la future maman.`,
      `Nous débutons l'atelier autour d'un temps d'échanges accompagné d'une boisson chaude et des quelques petites gourmandises bienveillantes.`,
      `Un temps de transmission ludique autour des changements physiques et psychiques, des hormones et de leurs rôles se fait entre vous et moi, dans une ambiance décontractée et chaleureuse.`,
      `Puis, nous passons à une transmission pratique autour des différents outils adaptés à tous : rebozo, massages, ballon, postures,bercements, peigne...`,
      `Vous repartez également avec des petits tips écrits qui vous accompagneront tout au long de la grossesse et de la naissance.`,
      `C'est une véritable  transmission bienveillante à destination de TOUS LES FUTURS PARENTS qui vous permet de repartir avec des clés concrètes mais aussi de vivre un temps de bien être en couple ou en famille dans une ambiance intimiste. Un temps rempli de douceur, de tendresse, de bienveillance et parfois de beaucoup d'humour.
      `,
    ],
    prestations: ["à domicile", "en cabinet"],
    duration: "1 heure",
    price: "45 euros",
    infos: [],
  },
  {
    id: 7,
    url: "fete-future-mere",
    image: "fete_future_mere.jpeg",
    title: "Fête de la future mère",
    content: [
      `Fêter la future mère pourquoi ? `,
      `À sept mois, l'enfant à naître est presque entièrement formé dans l'utérus maternel. À travers le monde et les époques et les différentes traditions, le septième mois de grossesse est souvent marqué par des cérémonies ou des fêtes particulières célébrant l'arrivée de l'enfant. `,
      `Afin de de mettre en lumière et d'honorer votre maternité, votre grossesse, la force de votre corps, votre souveraineté, la fête de la future mère vous est spécialement dédiée pour que "votre village" composé de diverses personnes dont des femmes prenne soin de vous et conscientise l'importance du soutien de la jeune mère. `,
      `
      C'est un temps qui vous est réservé, c'est un temps pour s'écouter, pour prendre confiance en ses capacités à donner naissance et à devenir mère. C'est un temps pour se retrouver et profiter d'un moment entre femmes. `,
      `C'est un temps mêlant bien être, joie de se retrouver et préparation de son mois d'or (40 jours après la naissance de bébé). C'est un temps durant lequel les femmes pourront créer des soins pour vous et mijoter des petits plats à congeler pour cette période transcendante qu'est le post partum.`,
      `
      Naître Ensemble, vous propose de co-animer un moment épuré, féminin, plein de sororité autour d'une décoration "pampa".`,
      `Une fête de la future mère avec Naître Ensemble ressemble à : `,
      `Ouverture de cérémonie d'un moment plein de sororité`,
      `Découverte des divers ateliers bien être autour de la fin de grossesse et du post partum (création d'huile de massage, soins post-partum...), échanges et gourmandises`,
      `Découverte de l'atelier cuisine post partum à réaliser entre femmes pour vous`,
      `Massage "bien naître" de la femme enceinte pendant que les femmes cuisinent pour vous`,
      `Temps suspendu entre femmes pour faire durer le petit nuage sur lequel vous serez après le massage durant lequel vous pourrez vous faire chouchouter par toutes les femmes (massage des mains, massage crânien, massage des pieds, bain de pieds et henné sur les mains, pieds et/ou ventre)`,
      `Clôture d'une cérémonie aimante et douce par des petit mots d'encouragements pour la future mère.  `,
      `Évidemment, c'est vous qui composez avec moi et avec les organisatrices de cette fête. Vous avez la possibilité d'ajouter ou de vous passer de ces propositions. `,
      `Pour organiser ce moment, je propose : `,
      `Un temps d'échange d'1h avec la future mère pour parler de ses besoins et ses désirs pour ce joli moment`,
      `Des échanges avec les participantes ou la personne ressource de la mère pour la répartition de l'organisation`,
      `Je met à votre disposition des éléments de déco "pampa" assez naturels, dans les tons blanc/beige/osier. Libre à vous de compléter cette décoration pour ajouter votre touche`,
      `Je mets également à disposition : des idées goûter à utiliser jusqu'à la naissance et en post partum et une liste de courses spéciale post partum pour préparer des plats à congeler pour la jeune mère`,
      `Je propose de disposer quelques ateliers à faire durant cette fête avec du matériel de soins pour prendre soin de soi entre femmes (bain de pieds, préparation d'huile de massage, soins post partum, sauna portatif pour les invitées)`,
      `Je vous offre du henné, vous aurez le choix entre un modèle ou une création faite par les femmes pour vous. Mais aussi des papiers à petits mots à glisser pour la mère et le bébé. `,
      `Je suis à vos côtés pour co-animer cette fête avec les femmes qui prendront soin de vous et qui font partie de votre village de soutien avant et après la naissance. L'idéal est d'échanger avec vous et de désigner une superwoman qui sera garante de l'organisation en amont et de l'après fête (aide au rangement,...) `,
    ],
    prestations: ["à domicile"],
    duration: "3 heure",
    price: "250 euros",
    infos: [],
  },
];

export default data;
