const data = [
  {
    id: 9,
    url: "rituel-bain-sensoriel",
    image: "rituel_bain_sensoriel.png",
    title: "Rituel du bain sensoriel® ",
    content: [
      ` Le rituel du bain sensoriel® qu'est ce que c'est ?`,
      ` C'est tout sauf un simple bain, c'est un réel accompagnement du post partum autour du bain de bébé.`,
      ` Le temps d'accueil du parent et de bébé :`,
      ` C'est avant tout un temps d'échanges entre vous parents et moi autour de la grossesse, de l'accouchement, de votre bébé, du devenir parent, du devenir famille, du retour à la maison, du bain, et de tout ce que votre cœur aura envie d'exprimer.`,
      ` En toute intimité, grâce à une écoute active et à la confiance que vous m'accorderez, vous serez libre de déposer votre vécu, vos ressentis, vos émotions, vos besoins dans cet espace que je vous offre.`,
      ` Je vous accompagne ensuite à l'emmaillotage physiologique de votre bébé pour ce bain et pour tous les autres bains à la maison. Un poupon me permettra de vous initier et vous, vous emmailloterez directement votre bébé.`,
      ` Le cœur du bain :`,
      ` Le temps du bain arrive et bébé entrera au creux de l'eau avec douceur et lenteur. Vos mains se juxtaposeront aux miennes pour finir par ce moment unique entre vous et votre bébé, rien qu'entre VOS MAINS. Vous êtes au COEUR du bain et bébé est notre petit éclaireur.`,
      `Dans ce bain, bébé retrouve des sensations in-utéro, il renoue un lien particulier avec l'eau, sa naissance, son vécu, ses émotions. À l'aide de bercements que vous apprendrez à reproduire facilement à la maison, vous observerez votre bébé différemment, vous découvrirez une autre façon de donner le bain, vous revivrez également des émotions, des sensations.`,
      `C'est un espace hors du temps, une bulle de confiance, de partage et de bien être, un accompagnement complet de la dyade ou de la triade parents/enfant.`,
      ` "Un bain de sens, un bain de lien, un bain d'amour et de confiance...". Tout se créé en fonction de votre histoire et celle de bébé.`,
      `​​​​L'après rituel, le temps cocoon :`,
      `​​Pour terminer ce rituel sensoriel et parce que le toucher est la première capacité sensorielle à apparaître chez le bébé in utero avant même la vue et l'ouïe, un temps d'initiation au massage bébé et à la réflexologie bébé émotionnelle® vous sera proposé. À l'aide d'un poupon de mon côté, vous serez les seuls à masser votre bébé s'il est disponible ou vous repartirez avec toutes les clés pour le reproduire à la maison.`,
      `Ambassadrice du bain sensoriel®, je vous accompagne en tant que parents à croire en vous, en vos capacités et en vos potentialités de parents, parce que vous avez tout en vous et que chaque parent est le parent qu'il faut pour son bébé.`,
    ],
    prestations: ["à domicile"],
    duration: "2h",
    price: "90 euros",
    infos: [
      `Réalisable dès la sortie de maternité`,
      `Idéalement avant les un mois de bébé`,
      `Possible jusqu'à 2 mois`,
      `L'âge corrigé est pris en compte jusq’à 3 mois pour les bébés nés prématurément`,
      `Tout le matériel est fourni lors de ma venue (baignoire sur pieds, matelas à langer, langes,...)`,
    ],
  },
  {
    id: 10,
    url: "massage-post-natal",
    image: "massage_post_natal.png",
    title: "Massage post natal",
    content: [
      `Un massage dédié à la femme après la naissance de bébé mais sans limite dans le temps car comme le dit Anna Roy la sage femme “le postpartum dure 3 ans”. Un massage enveloppant, aimant et revitalisant. Un massage qui vous fait ressentir que vous êtes importante.`,
      ` Je vous ferai profiter dans un premier temps d'un temps d'accueil autour d'une boisson revitalisante dédiée à la femme en période post partum.    `,
      ` Dans une ambiance tamisée et chaude ou aménagée selon l'approche snoezelen, un temps de bercement au rebozo vous sera offert pour soulager les tensions accumulées dans votre corps. Cette approche non invasive vous permettra d'appréhender le massage tout en douceur avant de lâcher prise totalement. `,
      `Vous profiterez ensuite d'un massage cocooning du corps complet dans la position la plus confortable pour vous qui libère les tensions liées à l'accouchement, le stress, l'anxiété et qui vous permet d'apprivoiser votre corps, ce corps qui a porté et donné la vie.    `,
      ` Un resserage du bassin à l'aide du rebozo clôturera le soin et vous permettra de ressentir enveloppement et contenance dans cette zone qui parfois peut se sentir "vide". Cette technique de fermeture du bassin permettra également à votre corps et à cette zone de clore cette étape dans votre vie de femme, et de laisser place à la nouvelle femme et mère que vous êtes.  `,
      `Les petits + chez Naître Ensemble :    `,
      `​​L'ambiance à choisir : tamisée/bougies ou ambiance snoezelen`,
      `L'huile de massage au choix : odeur gourmande à la prune et au coton ou odeur épicée d'orient à l'huile d'argan `,
      `La présence de bébé acceptée à définir ensemble, nous nous adaptons à l'aide du portage et de pause tétée/biberon si besoin`,
      `Le petit bandeau sur les yeux tout doux`,
    ],
    prestations: ["à domicile", "en cabinet"],
    duration: "1h30",
    price: `95 euros`,
    infos: [],
  },
  {
    id: 11,
    url: "rituel-rebozo",
    image: "soin_ribozo.gif",
    title: "Rituel Rebozo",
    content: [
      `Le rituel Rebozo est un soin ancestral donné par des femmes pour des femmes dans toutes cultures du monde. Ce soin accompagne la femme lors d'un changement majeur (mariage, naissance, deuil, ménopause, déménagement, 1ères menstruations, changement de travail, séparation...) ou tout simplement à toute femme qui souhaite prendre un temps pour soi, faire une pause, prendre du recul, se faire plaisir, se ressourcer, soutenir la libido...`,
      `Il m'a été transmis par Yael Flauder sage femme exerçant au Mexique.`,
      `Ce soin débute par une rencontre, un temps d'échanges autour d'une tisane spéciale aux plantes qui vous permet de réchauffer votre corps et de le préparer à recevoir ce soin, un temps qui vous permet de poser vos intentions dans ce soin et de conscientiser ce que vous vous apprêter à recevoir. Cette tisane sucrée et réchauffante vous suivra tout au long de votre soin.`,
      ` Dans une ambiance intimiste et purement féminine, nous continuons ce moment par un temps de massage enveloppant et revitalisant du corps entier, profond ou doux je suis à l'écoute de votre corps, vos sensibilités et vos besoins.`,
      `Vous profiterez ensuite d’un temps de sudation à l'intérieur d'un sauna ou dans un bain très chaud (au choix si vous le réalisez à votre domicile). Un véritable temps de nettoyage et d'introspection.`,
      `Nous passerons au resserage du corps de la tête aux pieds, un temps de fermeture et d'ouverture. `,
      ` Enfin, nous clôturerons le soin par un temps d'échanges autour de vos ressentis, vos émotions toujours accompagné de cette tisane et de douceurs revitalisantes.`,
      `Ce soin peut être réalisé :`,
      ` Environ 40 jours après l'accouchement ou au moment où vous vous sentez prête.`,
      ` Lorsque vous allaitez exclusivement, nous ferons en sorte d'attendre que les tétées soient un peu plus espacées.`,
      `Si vous avez vécu une césarienne, nous attendrons la fin de la cicatrisation (environ 4 à 6 semaines ou plus)`,
      `Il est possible de désigner une autre femme en qui vous avez confiance pour que nous formions un duo qui prend soin de vous lors du massage et du resserage du corps. Je transmet ce soin tel qu'il m'a été transmis de femme à femme sans attente et avec beaucoup de plaisir.`,
      `Il est possible aussi que bébé ne soit pas très loin dans la mesure où quelqu'un peut rester présent pour répondre à ses besoins. Nous jaugeons ensemble ce qui est le plus juste pour vous et votre lâcher prise.`,
    ],
    prestations: ["à domicile", "en cabinet"],
    duration: "3 heures",
    price: `250 euros`,
    infos: [],
  },
  {
    id: 12,
    url: "massage-bébé",
    image: "massage_bebe.png",
    title: "Massage bébé/enfant ",
    content: [
      `Le massage bébé/enfant c'est savoir utiliser tous les bienfaits du toucher, la première des capacités sensorielles qu'un enfant développe in-intéro.`,
      `À travers le massage des jambes et des pieds, du ventre, de la poitrine et des bras, du visage et du dos que je vous transmettrais à l'aide d'un poupon à mes côtés, vous découvrirez comment permettre à votre bébé de construire son identité physique, motrice et émotionnelle pour devenir un adulte à l'aise dans son corps et dans sa tête à l'avenir. Vous découvrirez aussi comment favoriser et soutenir la motricité de votre bébé et la connaissance de son schéma corporel.`,
      `Ces ateliers de massages vont aussi et surtout être des moments de partage, d'échanges et de création de lien entre vous et votre bébé ! Des moments remplis de tendresse et d'amour entre vous.`,
      `Ces massages sont inspirés des massages du monde (nordique, indien, africain) et de la réflexologie plantaire. Les bienfaits des massages sont multiples (nourrir la peau, prendre conscience de son schéma corporel, détendre, apaiser, libérer les émotions, favoriser l’endormissement, renforcer le lien parents/enfant, stimuler les différents systèmes (lymphatique, sanguin, musculaire…), favoriser un meilleur développement physique, émotionnel, moteur, psychique, soulager les maux de ventre/dentaires, favoriser les rituels, favoriser un éveil harmonieux, apporter une sécurité affective, découvrir les compétences incroyables de bébé)`,
      `Un atelier concrètement c'est :`,
      `Créer son huile de massage bio`,
      `Apprendre des mouvements de massage en fonction de l'âge et de la disponibilité de votre enfant`,
      `Aborder une thématique liée au bébé (pleurs, sommeil, coliques, émotions)`,
      `Apprendre une posture de yoga bébé`,
      `Suite à l'atelier vous aurez accès gratuitement à l’application « Graine de massage » qui vous permettra de voir et revoir les massages appris ensemble.`,
      `L'atelier massage bébé/enfant est possible de la naissance jusq'aux 8 ans de l'enfant.`,
    ],
    prestations: ["à domicile", "en cabinet"],
    duration: "1h",
    price: `60 euros `,
    infos: [
      `Huile bio fournie`,
      `Livret de massage version papier fourni en fin de séance`,
      `Réservation à la séance ou forfaits possibles `,
      `Vous voulez organiser un atelier à plusieurs ? C'est possible en cabinet ou à domicile`,
    ],
  },
  {
    id: 13,
    url: "atelier-de-portage",
    image: "portage.png",
    title: "Atelier de portage",
    content: [
      `​​Atelier idéal après l'atelier découverte du portage`,
      ` Vous portez déjà mais :`,
      `Bébé est né et les débuts de portage ont besoin d'être ajustés ?`,
      `Bébé a grandi et vous avez besoin de trouver un nouveau moyen de portage adapté à son niveau de développement et à votre confort ?`,
      `Nous reverrons ensemble en pratique ce qui correspond à votre bébé et à vous en tant que porteur et nous ajusterons ensemble les réglages si besoin.`,
      `Vous pourrez tester diverses marques, nous discuterons de vos essais, du confort de bébé et du vôtre.`,
      `Le meilleur moyen d'éviter les achats inutiles est d'essayer et d'être accompagné par une professionnelle formée.`,
      `Alors n'attendez plus et faites confiance à la magie du portage...`,
    ],
    prestations: ["à domicile", "en cabinet"],
    duration: "1h30",
    price: `70 euros`,
    infos: [],
  },
  {
    id: 14,
    url: "soutien-en-allaitement",
    image: "allaitement.png",
    title: "Soutien en allaitement",
    content: [
      `​​Vous allaitez mais vous avez des questionnements qui ne nécessitent pas une consultation auprès d'un professionnel de santé (sage femme, médecin,...) ou d'une consultante en lactation (IBCLC) ? `,
      `Vous avez besoin d'échanger sur cet allaitement en particulier et sur votre quotidien de mam'allaitante ? `,
      `Vous souhaitez revoir les bases de l'allaitement ?`,
      `Vous êtes épuisée et vous cherchez des solutions pour poursuivre ou non en douceur ?`,
      `Vous avez des doutes pour une orientation ? Je suis présente pour vous soutenir, vous accompagner dans le cadre de mes compétences et vous orientez vers le professionnel nécessaire dans votre suite d'allaitement.`,
    ],
    prestations: ["à domicile", "en cabinet"],
    duration: "1h",
    price: `50 euros`,
    infos: [],
  },
  {
    id: 15,
    url: "service-doula-dodo",
    image: "service_doula_dodo.jpeg",
    title: "Service doula dodo",
    content: [
      `​​Le service doula dodo quésako? `,
      `Vous êtes parent d'un bébé et vous n'avez pas de soutien autour de vous ? `,
      `Vous êtes deux mais les besoins de bébé ne vous permettent pas encore de vous reposer suffisamment ? `,
      `Vous êtes en hypervigilance tout le temps depuis la naissance de bébé et vous n’arrivez pas à vous reposer ?`,
      `Vous êtes tout simplement épuisé et vous auriez besoin d'une bonne nuit de sommeil ?`,
      `Vous souhaitez offrir une nuit de sommeil à un futur parent plutôt que la traditionnelle et énième peluche ?`,
      `Permettez moi d'être à vos côtés durant cette période post partum pour vous soutenir de façon concrète en vous offrant tout simplement la possibilité de vous reposer et d'être suffisamment sécurisé pour lâcher prise sur la surveillance de bébé le temps d'une nuit, de quelques heures...`,
      `De façon temporaire et uniquement en votre présence au domicile (sauf cas exceptionnel), je vous offre la possibilité de faire appel à moi en fonction de vos besoins.`,
      ` Nous établissons sur devis le nombre d'heures souhaitées et nous organisons une rencontre préalable afin de faire connaissance avec vous et votre bébé.`,
      `Je suis votre fée du sommeil chers parents. Une main tendue pour vous permettre de vous reposer et de récupérer afin d'être plus disponible pour votre bébé ? Oui !`,
      `Alors à quand remonte votre dernière nuit complète ?`,
      `Un cadeau idéal à faire à tous les parents du monde : des heures de sommeil.`,
    ],
    prestations: ["à domicile"],
    duration: "1h",
    price: `35 euros`,
    infos: [
      `Glisser la demande sur votre liste de naissance ou offrez une carte cadeau pour une nuit de sommeil`,
      `Forfait 1 nuit (8h) : 200 euros`,
      `Forfait 4 nuits : 750 euros`,
      `CESU possible`,
    ],
  },
  {
    id: 16,
    url: "aide-à-domicile-postpartum",
    image: "aide_domicile_post_partum.jpeg",
    title: "Aide à domicile post partum ",
    content: [
      `Ma mission ? Vous soulager dans ce quotidien totalement bousculé`,
      `À chacune de mes visites, vous me poserez vos besoins réels.`,
      ` Il peut s'agir :`,
      `De prendre en charge la gestion de votre maison : ménage, linge, préparation de repas, courses`,
      `De vous soutenir émotionnellement en vous écoutant, en accueillant votre vécu, vos ressentis, vos angoisses...`,
      `De vous accompagner dans votre nouveau quotidien de parent et de répondre à vos questions concernant :les soins (change, bain, routine etc), l'allaitement (rythme, positions, douleurs etc.) ou le biberonnage,le sommeil (cycles, réveils nocturnes, siestes etc), les pleurs (décharge, inconfort, fatigue etc.)`,
      `Le tout avec bienveillance, empathie et non jugement ! `,
    ],
    prestations: ["à domicile"],
    duration: "1h",
    price: `35 euros`,
    infos: [
      `Naître Ensemble est partenaire du réseau OHMAMACARE pour vous faire profiter d'avantages`,
      `50% crédit d'impôt`,
      `Devis gratuit sur www.ohmamacare.fr`,
    ],
  },
  {
    id: 17,
    url: "reflexologie-bebe-émotionnelle",
    image: "reflexologie_bebe.png",
    title: "Réflexologie bébé émotionnelle®",
    content: [
      `Pourquoi réaliser un atelier de réflexologie bébé émotionnelle® ? .`,
      `Parce que le vécu de la vie intra-utérine et de la naissance peuvent expliquer de nombreux maux dans la vie quotidienne de bébé.`,
      `Parce que la grossesse est une véritable explosion de différentes émotions et que nous portons tous en nous des empreintes émotionnelles (issuent de la mère, du père et des générations précédentes)`,
      `Tous les parents recherchent des explications à certaines réactions de bébé (pleurs, sommeil difficile, reflux...etc)`,
      `La réflexologie bébé émotionnelle® permet une prise en compte des maux, associée à la parole et au toucher plantaire`,
      `Quelques questions et vos observations concernant votre enfant nous permettront de repérer les liens entre ses maux et leur origine émotionnelle`,
      `À l'aide de différents protocoles spécifiques en fonction des maux de bébé, je vous apprendrai à l'aide de mon poupon à réaliser les gestes sur votre bébé`,
    ],
    prestations: ["à domicile", "en cabinet"],
    duration: " 1h ",
    price: `60 euros`,
    infos: [
      `La réflexologie bébé émotionnelle® n'est pas thérapeutique et ne se substitue pas à un suivi médical.`,
      `Elle intervient en soutien aux différentes maux du quotidien : maux de ventre, petit virus du quotidien, les problèmes de la sphère ORL, les douleurs, les angoisses, les phobies, les émotions difficiles...`,
      `De la naissance à 6 ans`,
      `Durant l'atelier, l'huile de massage bio est fournie`,
    ],
  },
  {
    id: 18,
    url: "rendez-vous-personnalise",
    image: "reflexologie_bebe.png",
    title: "Rendez vous personnalisé",
    content: [
      `Après la naissance, vous ressentez le besoin de poser vos questions à une personne formée, de vous sentir écoutée, comprise et accompagnée sur des sujets liés à vous, votre accouchement, votre bébé, vos enfants (puériculture, éducation, soins, aménagement de l'espace, développement de l'enfant, activités, jeux...) ? `,
      `Les rendez-vous personnalisés après la naissance se font sur mesure en fonction de vos besoins et ceux de votre enfant.`,
      `Vous souhaitez mettre en place une éducation bien traitante sans vous y perdre ? `,
      `La motricité libre est un concept dont vous avez entendu parler et vous souhaitez la mettre en place à la maison ? `,
      `Vous ne savez pas par où commencer dans les activités avec bébé ou dans les achats de jeux ? `,
      `Vous avez envie d'apprendre à signer quelques mots avec bébé, quelques comptines et à lire avec bébé ? `,
      `Dans votre quotidien avec votre enfant, certains moments sont plus difficiles que d'autres et vous avez besoin d'un regard sur la situation ? `,
      `Jouer avec votre enfant n'est pas inné, et vous souhaitez apprendre à adopter une posture qui vous permette de vivre des moments de qualité autour du jeu ? `,
      `Vous souhaitez vous offrir une heure d'activité qui change de l'ordinaire ? (parcours de motricité, éveil sensoriel, bacs sensoriels, manipulation,...)`,
      `Tout est possible sur demande. `,
    ],
    prestations: ["à domicile", "au cabinet"],
    duration: "1 heure",
    price: "50 euros",
    infos: [
      `Un échange téléphonique nous permet de cerner vos premiers besoins`,
      `J'utilise mon approche d'éducatrice, d'accompagnante et de doula pour vous offrir une approche intégrative qui répondra à vos besoins et ceux de votre enfant`,
      `Seule, en couple ou en famille`,
    ],
  },
];

export default data;
